// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Notes.WebApi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Note
    {
        /// <summary>
        /// Initializes a new instance of the Note class.
        /// </summary>
        public Note()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Note class.
        /// </summary>
        public Note(string id = default(string), string text = default(string), string author = default(string), System.DateTime? updated = default(System.DateTime?))
        {
            Id = id;
            Text = text;
            Author = author;
            Updated = updated;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "author")]
        public string Author { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updated")]
        public System.DateTime? Updated { get; set; }

    }
}
